# Generated by Django 3.1.1 on 2020-11-11 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalescaleApp', '0003_auto_20201107_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='Length',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('widthSegments', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='angle',
        ),
        migrations.RemoveField(
            model_name='image',
            name='area',
        ),
        migrations.RemoveField(
            model_name='image',
            name='length',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
        migrations.RemoveField(
            model_name='image',
            name='widthSegments',
        ),
        migrations.AddField(
            model_name='image',
            name='notes',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='altitude',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='focalLength',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='pixelDimension',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('length', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whalescaleApp.length')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='whalescaleApp.image')),
            ],
        ),
        migrations.AddField(
            model_name='length',
            name='measurement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whalescaleApp.measurement'),
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('area', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whalescaleApp.measurement')),
            ],
        ),
        migrations.CreateModel(
            name='Angle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('angle', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('measurement', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whalescaleApp.measurement')),
            ],
        ),
    ]
