# Generated by Django 3.1.1 on 2020-11-12 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whalescaleApp', '0004_auto_20201110_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angle',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='area',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='length',
            name='measurement',
        ),
        migrations.AddField(
            model_name='angle',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whalescaleApp.image'),
        ),
        migrations.AddField(
            model_name='area',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whalescaleApp.image'),
        ),
        migrations.AddField(
            model_name='length',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='whalescaleApp.image'),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
    ]
