# Generated by Django 3.1.3 on 2020-11-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whalescaleApp', '0006_length_bezierfit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angle',
            name='angle',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='area',
            name='area',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='altitude',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='focalLength',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='pixelDimension',
            field=models.DecimalField(decimal_places=10, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='length',
            name='length',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='width',
            name='width',
            field=models.DecimalField(decimal_places=5, max_digits=15, null=True),
        ),
    ]
